import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {createDeposits,depositPatches,insideDeposit} from '../public/deposits.js';
const sandbox={console,setTimeout,clearTimeout,addEventListener(){},removeEventListener(){}};sandbox.window=sandbox;
vm.runInNewContext(readFileSync(new URL('../public/vendor/babylon-9.28.0.js',import.meta.url),'utf8'),sandbox);
const B=sandbox.BABYLON,engine=new B.NullEngine(),scene=new B.Scene(engine);
const {instance:{exports:c}}=await WebAssembly.instantiate(readFileSync(new URL('../public/planet_geometry.wasm',import.meta.url)),{});
const count=c.generate_blue(8,.02,23),tiles=c.tile_count();
const matrices=new Float32Array(c.memory.buffer,c.matrices_ptr(),count*16).slice(),ids=new Uint32Array(c.memory.buffer,c.tile_ids_ptr(),count).slice(),kinds=new Uint32Array(c.memory.buffer,c.kinds_ptr(),count).slice();
const centers=new Float32Array(c.memory.buffer,c.tile_centers_ptr(),tiles*3).slice(),features=new Uint32Array(c.memory.buffer,c.features_ptr(),tiles).slice(),neighbors=new Uint32Array(c.memory.buffer,c.tile_neighbors_ptr(),tiles*6).slice();
const patches=depositPatches(centers,features,neighbors,8);
assert.equal(patches.length,features.filter(x=>x&2).length);
assert(patches.every(p=>p.owners.every(id=>features[id]&2)));
assert(patches.every(p=>insideDeposit(p,p.center)));
assert.deepEqual(patches,depositPatches(centers,features,neighbors,8));
const model=JSON.parse(readFileSync(new URL('../public/models/deposit_01.json',import.meta.url))).parts[0];
let mask;const d=createDeposits(B,scene,value=>mask=value,model);
d.update(c,matrices,ids,kinds,8);
const positions=Array.from(d.mesh.getVerticesData('position')),indexCount=d.mesh.getTotalIndices();
assert(indexCount>0);assert.equal(d.cutout,undefined);assert.equal(d.mesh.getVerticesData('uv').length,positions.length/3*2);assert(positions.every(Number.isFinite));
const patch=patches.find(p=>p.owners.length===1&&mask(p.center,p.owners[0])===0);assert(patch);
const tile=patch.owners[0];
assert(Math.hypot(...d.surfacePoint(patch.center,tile))>=Math.hypot(...patch.center),'Deposit must not lower the terrain surface');assert.equal(mask(patch.center,tile),0);
d.setOccupied(new Set([tile]));assert(d.mesh.getTotalIndices()<indexCount);assert.equal(mask(patch.center,tile),1);
d.setOccupied(new Set());assert.equal(d.mesh.getTotalIndices(),indexCount);assert.deepEqual(Array.from(d.mesh.getVerticesData('position')),positions);assert.equal(mask(patch.center,tile),0);
d.show(false);assert.equal(d.mesh.isEnabled(),false);assert.equal(mask(patch.center,tile),1);
d.show(true);assert.equal(d.mesh.isEnabled(),true);assert.equal(mask(patch.center,tile),0);
scene.dispose();engine.dispose();
console.log('Deposits: deterministic feature-only patches, deposit model, finite conforming geometry, grass exclusion, construction removal and demolition restoration pass.');
