import {METERS_TO_TILE_UNITS} from '../public/model-units.js';
import {createRegions} from '../public/editor/model-data.js';
import assert from 'node:assert/strict';
import {createRequire}from'node:module';
import{readFileSync}from'node:fs';
import{opaqueMaterial,nearestSwatch,buildingPaletteMaterial}from'../public/palette-material.js';
import{loadHouseModel}from'../public/house-model.js';
import{mergeHousingParts}from'../public/housing-cluster.js';
import{subdivideBuildingGeometry,updateBuildingBounds}from'../public/building-wrap.js';
const require=createRequire(import.meta.url),base=require('../public/vendor/babylon-9.28.0.js'),B={...base,RawCubeTexture:class extends base.BaseTexture{constructor(scene){super(scene);}}};
const source=JSON.parse(readFileSync(new URL('../public/models/house_01.json',import.meta.url)));
const generated=createRegions(source.parts,JSON.parse(readFileSync(new URL('../public/models/palette.json',import.meta.url))));generated.ao[0][0]=-2;generated.ao[0][1]=3;const authored={version:1,models:{house_01:generated},appearances:{house:{name:'House',colors:generated.colors}},bindings:{house_01:'house'}};
const expectedTriangles=source.parts.reduce((n,p)=>n+p.indices.length/3,0);
const engine=new B.NullEngine(),scene=new B.Scene(engine),original=globalThis.fetch;
globalThis.fetch=async(url)=>({ok:true,json:async()=>url==='models/library.json'?{models:[]}:url==='models/authoring.json'?authored:JSON.parse(readFileSync(new URL('../public/'+url,import.meta.url)))});
const oldDocument=globalThis.document,oldBitmap=globalThis.createImageBitmap;
globalThis.createImageBitmap=async()=>({width:1,height:1,close(){}});globalThis.document={createElement:()=>({getContext:()=>({clearRect(){},drawImage(){},getImageData:()=>({data:new Uint8Array([128,128,128,255])})})})};
const fetchBase=globalThis.fetch;globalThis.fetch=async(...args)=>({...await fetchBase(...args),blob:async()=>new Blob()});
try{const make=await loadHouseModel(B,scene),root=new B.TransformNode('home',scene),shadows={addShadowCaster(){},removeShadowCaster(){}},underwater={renderList:[]};root.position.y=1.02;root.scaling.setAll(1/8);make(root,0,0,0,1,null,shadows,underwater);assert(root.getChildMeshes().every(mesh=>mesh.scaling.equals(B.Vector3.One().scale(METERS_TO_TILE_UNITS))));assert.equal(root.getChildMeshes().length,source.parts.length);assert(root.getChildMeshes().every(mesh=>mesh.position.y===0));const atlas=root.getChildMeshes().find(m=>m.material.name==='building-palette').material;const shared=opaqueMaterial(B,scene,'shared-check',null,{atlas:true});assert.equal(atlas.albedoTexture,shared.albedoTexture);assert.equal(atlas.metallicTexture,shared.metallicTexture);assert.equal(atlas.ambientTexture.coordinatesIndex,1);assert(scene.metadata.palette.swatches.includes(nearestSwatch(scene,[.4,.6,.2])));shared.dispose();assert.equal(atlas,buildingPaletteMaterial(B,scene));assert.equal(new Set(root.getChildMeshes().map(m=>m.material)).size,1);assert.equal(root.getChildMeshes().reduce((n,m)=>n+m.getTotalIndices()/3,0),expectedTriangles);mergeHousingParts(B,root,scene,shadows,underwater);for(const mesh of root.getChildMeshes()){const geometry=subdivideBuildingGeometry({positions:mesh.getVerticesData('position'),normals:mesh.getVerticesData('normal'),uvs:mesh.getVerticesData('uv'),uvs2:mesh.getVerticesData('uv2'),ao:mesh.getVerticesData('modelAO'),indices:mesh.getIndices()},1.02,1/8);assert(geometry.ao.some(v=>v<0));assert(geometry.ao.some(v=>v>1));assert(geometry.positions.every(Number.isFinite));assert.equal(geometry.uvs2.length,geometry.positions.length/3*2);assert(geometry.uvs2.some(v=>v>0));const data=new B.VertexData();Object.assign(data,geometry);data.applyToMesh(mesh);updateBuildingBounds(B,mesh,root.position);}assert.equal(underwater.renderList.length,1);assert.equal(root.getChildMeshes()[0].material.alpha,1);console.log('House: shared building material, reflective pane atlas, AO UV2, merged geometry and wrapping bounds pass.');}finally{globalThis.fetch=original;globalThis.document=oldDocument;globalThis.createImageBitmap=oldBitmap;scene.dispose();engine.dispose();}
