import assert from 'node:assert/strict';
import {createOptimisticActions} from '../public/optimistic-actions.js';
const settle=()=>new Promise(resolve=>setImmediate(resolve));
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
let state=[],sent=[],changes=0,statusError=null;
const requests=[];
const queue=createOptimisticActions({apply({args}){if(state.includes(args[0]))return 1;state.push(args[0]);return 0;},restore(snapshot){state=[...snapshot];},send(command){sent.push(command.args[0]);const request=deferred();requests.push(request);return request.promise;},refresh:async()=>['a','b'],changed(){changes++;},status(error){statusError=error;}});
assert.equal(queue.enqueue('build','a'),0);assert.deepEqual(state,['a']);assert.equal(changes,1);
assert.equal(queue.enqueue('build','b'),0);assert.deepEqual(state,['a','b']);assert.deepEqual(sent,['a']);
assert.equal(queue.enqueue('build','b'),1);assert.equal(queue.pending,2);
requests[0].resolve(['a']);await settle();assert.deepEqual(state,['a','b']);assert.deepEqual(sent,['a','b']);
requests[1].resolve(['a','b']);await settle();assert.equal(queue.pending,0);assert.deepEqual(state,['a','b']);
queue.enqueue('build','c');queue.enqueue('build','d');requests[2].reject(Error('Transaction rejected'));await settle();
assert.deepEqual(state,['a','b']);assert.equal(queue.pending,0);assert.deepEqual(sent,['a','b','c']);assert.equal(statusError.message,'Transaction rejected');
queue.enqueue('build','e');assert.deepEqual(state,['a','b','e']);requests[3].resolve(['a','b','e']);await settle();
console.log('Immediate local updates, serialized submissions, pending replay, local rejection, rollback and recovery pass.');
let recovered=[],recovery=deferred(),request=deferred(),lastError;
const failed=createOptimisticActions({initial:['confirmed'],apply({args}){recovered.push(args[0]);return 0;},restore(s){recovered=[...s];},send:()=>request.promise,refresh:()=>recovery.promise,changed(){},status(e){lastError=e;}});
failed.enqueue('build','pending');request.reject(Error('Timeout'));await settle();assert.deepEqual(recovered,['confirmed']);assert.equal(failed.enqueue('build','during-resync'),1);
recovery.reject(Error('Offline'));await settle();assert.equal(failed.enqueue('build','still-offline'),1);assert.match(lastError.message,/reload to reconnect/);
console.log('Unavailable reconciliation restores confirmed state and blocks additional submissions.');
