import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {questDetails} from '../public/quests.js';
const {instance:{exports:c}}=await WebAssembly.instantiate(readFileSync(new URL('../public/planet_geometry.wasm',import.meta.url)),{});
c.generate_blue(8,.02,23);
const n=c.tile_count(),surfaces=new Uint32Array(c.memory.buffer,c.surfaces_ptr(),n).slice(),features=new Uint32Array(c.memory.buffer,c.features_ptr(),n).slice(),neighbors=new Uint32Array(c.memory.buffer,c.tile_neighbors_ptr(),n*6).slice();
const dry=Array.from(surfaces.keys()).filter(i=>surfaces[i]);
const adjacent=i=>Array.from(neighbors.slice(i*6,i*6+6)).filter(j=>j<n&&surfaces[j]);
const commons=dry.find(i=>adjacent(i).length>=4),homes=adjacent(commons).slice(0,4);
const dock=dry.find(i=>i!==commons&&!homes.includes(i)&&c.industry_valid_sides(i,3));
const quarry=dry.find(i=>i!==commons&&i!==dock&&!homes.includes(i)&&(features[i]&2));
const factory=dry.find(i=>![commons,dock,quarry,...homes].includes(i));
const pool=()=>Array.from(new Uint32Array(c.memory.buffer,c.industry_pool_ptr(),3));
const until=(predicate,label)=>{for(let i=0;i<3600&&!predicate();i++)c.industry_advance(1);assert(predicate(),label);};
assert.equal(pool()[1],2);assert.equal(c.industry_unlocked(2),1);assert.equal(c.industry_unlocked(3),0);
assert.equal(c.industry_build(homes[0],2),0);assert.equal(pool()[1],1);
assert.equal(c.industry_build(homes[1],2),0);assert.equal(pool()[1],1);assert.equal(c.industry_tutorial(),1);assert.equal(c.industry_unlocked(3),1);
for(let i=0;i<10;i++)c.industry_refresh();assert.equal(pool()[1],1);
assert.equal(c.industry_build(dock,3),0);assert.equal(pool()[1],0);
until(()=>c.industry_tutorial()===2,'fish quest completes');assert.equal(c.industry_population(),10);assert.equal(pool()[1],2);
assert.equal(c.industry_unlocked(0),1);assert.equal(c.industry_unlocked(1),1);assert.equal(c.industry_unlocked(4),0);
assert.equal(c.industry_build(quarry,0),0);assert.equal(c.industry_tutorial(),2);assert.equal(c.industry_produced(0),0);
assert.equal(c.industry_build(factory,1),0);assert.equal(c.industry_tutorial(),3);assert.equal(pool()[1],2);assert.equal(c.industry_produced(1),0);
assert.equal(c.industry_workers(),10);for(const kind of [0,1,3])assert.equal(c.industry_productivity(kind),50);
for(let i=0;i<10;i++)c.industry_refresh();assert.equal(pool()[1],2);
for(const h of homes.slice(2))assert.equal(c.industry_build(h,2),0);assert.equal(pool()[1],0);
until(()=>c.industry_population()===20,'four fed houses grow to twenty');assert.equal(c.industry_tutorial(),4);assert.equal(c.industry_unlocked(4),1);assert.equal(pool()[1],3);
for(let i=0;i<10;i++)c.industry_refresh();assert.equal(pool()[1],3);
assert.equal(c.industry_build_cost(4),3);assert.equal(c.industry_build(commons,4),0);
until(()=>c.industry_tutorial()===5,'Commons quest completes');until(()=>c.industry_population()===40,'full capacity is ten per house');
for(const h of homes)c.industry_remove(h);assert.equal(c.industry_population(),0);
for(const kind of [0,1,3,4])assert.equal(c.industry_unlocked(kind),1);
const peak=c.industry_peak_population(),stage=c.industry_tutorial(),produced=[0,1,2].map(r=>c.industry_produced(r));
c.industry_reset();c.industry_restore_progression(peak,stage,...produced);c.industry_refresh();
assert.equal(c.industry_population(),0);for(const kind of [0,1,3,4])assert.equal(c.industry_unlocked(kind),1);assert.equal(pool()[1],2);
c.industry_reset();c.industry_restore_progression(0,6,0,0,0);assert.equal(c.industry_unlocked(3),0);
console.log('Tutorial: immediate chain completion, full workforce efficiency, expansion/Commons rewards exactly once, persistent unlocks and completion pass.');

const progress={stage:2,homes:2,fed:2,population:10,produced:[0,0,0],quarries:0,factories:0,covered:0};
assert.deepEqual(questDetails(progress).rows[0],{label:'Build a quarry',value:0,target:1,kind:0});
const chainQuest=questDetails({...progress,quarries:1});
assert.equal(chainQuest.phase,3);assert.equal(chainQuest.rows[1].kind,1);assert.equal(chainQuest.reward,2);
assert.equal(questDetails({...progress,stage:3}).reward,3);
assert.equal(questDetails({...progress,stage:4}).phase,5);
