import assert from 'node:assert/strict';
import {rememberedWallet,rememberWallet,forgetWallet,restoreWallet} from '../public/remembered-wallet.js';

const values=new Map(),storage={getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};
let available=[],calls=[];
const wallets={list:()=>available,silentConnect:async(address,name)=>{calls.push({address,name});return address;}};
assert.equal(await restoreWallet(storage,wallets),null);
rememberWallet(storage,'owner','Phantom');
assert.deepEqual(rememberedWallet(storage),{address:'owner',name:'Phantom'});
assert.equal(await restoreWallet(storage,wallets),null);
assert.equal(calls.length,0);
available=[{name:'Backpack'}];
assert.equal(await restoreWallet(storage,wallets),null);
assert.equal(calls.length,0);
available.push({name:'Phantom'});
assert.equal(await restoreWallet(storage,wallets),'owner');
assert.deepEqual(calls,[{address:'owner',name:'Phantom'}]);
wallets.silentConnect=async()=>null;
assert.equal(await restoreWallet(storage,wallets),null);
wallets.silentConnect=async()=> 'different-owner';
assert.equal(await restoreWallet(storage,wallets),null);
forgetWallet(storage);
assert.equal(rememberedWallet(storage),null);
assert.equal(await restoreWallet(storage,wallets),null);
values.set('interstellar-connected-wallet-v1','invalid JSON');
assert.equal(rememberedWallet(storage),null);
const unavailable={getItem(){throw Error('blocked');},setItem(){throw Error('blocked');},removeItem(){throw Error('blocked');}};
assert.equal(rememberedWallet(unavailable),null);
rememberWallet(unavailable,'owner','Phantom');forgetWallet(unavailable);
console.log('Wallet restoration: remembered provider, delayed discovery, denied restore, changed account, disconnect, and unavailable storage pass.');
